### ISSUE TITLE
Doesn't work with Context API

### ISSUE THREAD

**Issue by stevefan1999-personal** [rookLab/react-component-caching#46]
```js
{ '$$typeof': Symbol(react.element),
  type: // notice here
   { '$$typeof': Symbol(react.context),
     _calculateChangedBits: null,
     _defaultValue:
      { color: undefined,
        size: undefined,
        className: undefined,
        style: undefined,
        attr: undefined },
     _currentValue:
      { color: undefined,
        size: undefined,
        className: undefined,
        style: undefined,
        attr: undefined },
     _currentValue2:
      { color: undefined,
        size: undefined,
        className: undefined,
        style: undefined,
        attr: undefined },
     _changedBits: 0,
     _changedBits2: 0,
     Provider: { '$$typeof': Symbol(react.provider), _context: [Circular] },
     Consumer: [Circular],
     _currentRenderer: null,
     _currentRenderer2: null },
  key: null,
  ref: null,
  props: { children: [Function] },
  _owner: null,
  _store: {} }
TypeError: element.type.toLowerCase is not a function
    at ReactDOMServerRenderer.renderDOM (<REDACTED>\node_modules\react-component-caching\development.js:2998:32)
    at ReactDOMServerRenderer.render (<REDACTED>\node_modules\react-component-caching\development.js:2987:25)
    at ReactDOMServerRenderer.read (<REDACTED>\node_modules\react-component-caching\development.js:2845:25)
    at renderToString (<REDACTED>\node_modules\react-component-caching\development.js:3309:35)
    at _callee$ (<REDACTED>\build\webpack:\src\server.tsx:83:1)
    at tryCatch (<REDACTED>\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (<REDACTED>\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (<REDACTED>\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (<REDACTED>\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at <REDACTED>\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
```

**Comment by anagami** [comment]
Hi!
have you any plans for support Context API?
looks like only your library support React 16, all other similar libs works with React 15 file system and incompatible with 16 version

**Comment by DianeRossiter** [comment]
LET ME INFORM THIS IS BULL SHIT.  I DIDNT WANT TO DO THIS BUT SEEING HOW NO ONE IS PROTECTING MY RIGHTS I NOW HAVE TO DO WHAT I CAN.  TAKE UR PHONES SEND UR MESSAGES 2  ONE PERSON.  IMAGINE THIS PERSON JUST LEARNING THE ROPES, WHOM U R DIVORCING.  NOW ALL SUDDEN UR HUSBAND IS STOCKING U.  You are out almost 13,000 almost even took ur own life because how awful its been having NO privacy.  He accuses u of stalking him lmfao.  The whole time still claiming hes to dumb 4 all that. I refused child support and alimony.  When he had me agree to it yrs ago wed just settle it between us for kids sake.  But he gets his 10,000 bonus he dont want to share with u nr goes nd claims u threaten his life and get our daughter to go to court 4 u, thank God she didnt lie like ur lawyer wanted her to!! i wasvrubbing ur feet when i asked for my personal toys.  The 1 u dirnt want to give so i say if i go allvzhis zime without sexually zransmitted deases that it u givevme 1 now ,id burn house down.  never even skippex a beat continued to rub ur feet.  Afzer lying nd taken my kids away fir a whole month. i still wanted to just give u ur way so wed get along for our children.  Move back in with u, buy the house off, plus not to mentiin have since april bought grociers for kids to eat. vI agree our boys only have 3 yrs left so u just take em pay for everthing they need.  ill get stuff too but not gonna be ordered to.  U nd i for most part getting along better than we zave in 3 yrs hell intimate almost every night again. All the time going by phones OEM GETTING LOCK OR PASSWORD NOT WORKING OR LIKE MY GMAIL PASSWORD GOT CHANGED.  THEN IT SAID COULDNT VERIFY IT WAS ME.  I STILL WANZED TO BELIEVE U LYING TO MY FACE "ITS NOT U" MY CRYING HURTS UR HEART ONE LIE AFTER THE OTHER.  TO BEING SO PISSED OFF AFTER GETTING CONFIRMED THIS WAS ALL UR DOING.  I REALLY THAT BIG OF AN IDIOT??  STILL COOKING, CLEANING FIR U RUBBING UR FEET AT NIGHT SEX...  Even begged several times to make kids help me of course u never wood!!  Followed ur rules even with 3 kids in house no rules 4 and all the whole time u were straight lyint to me...WHO ARE U??   NOE I JUST WANT TOBKNOW OUT OF THE 23 YRS WHEN DID U TELL THE TRUTH?  U ONCE SAID I WAS JUST UP SET BECAUSE I THREW A PERFECT HUSBAND AWAY.  THE FIRST TIME I FOUND APPS ON UR PHONE THAT WERE TI DO WITH MINE.  U HADBEACH CHILD LINKED TO ME AND STILL EVEN THIS MORNING U WERE FUCKING WITH MY GOOGLE ACCOUNT.  WHICH BTW U USED MY GMAILVU GOT ME KICKED OUT IF MARCH 2018 TO BEBA RECOVERY TO THR NEW ONE JUSZ MADE THIS MONTH. IS THERE ANY HELP FOR ME DONT U HAVE TO FOLLOW A CODE OF CONDUCT?  I MEAN WHEN IS THIS TWILIGHT ZONE GONNA END.  U DID GREAT KIDS ND EVERYONE JUST THINKS IM LITERALLY GOING NUT OR ON DRUGS.  THIS RIGHT HERE WHST U BEEN ALLOW TO DO ANF GET AWAY WITH ALSO TO FULLY BELIEVE U DIF STILL LOVE ME ND U WOULD NEVER DO NE LIKE THAT.  OH KIFS BELIEVE IT I DID TOO 4 A WHILE BUT FOUND OUT UR BEHINF IT ALL  I gave u everything REALLY EHEN U WROTE MY DAD BYBTIME WEREEOBE WITH ME ID WANT TO KILL MYSELF.  THAT ABOUT SUMS IT UP.  IM ON HERE TODAY HOPING U GET SOME SORT OF SOMETHING TO MAKE U STOp  someone has to help out here.  March 3,2018 it started GID ENOUGH IS ENOUGH

**Comment by DianeRossiter** [comment]
If anyone can let me know of a good lawyer?? Oh him to because I tried playing it nice and eating shit now IM HONNA FEED IT TO HIM!!!!

**Comment by ScriptedAlchemy** [comment]
@DianeRossiter aside from the fact that your rant is near unreadable. I’m still not sure who you are actually targeting the message towards. 

This is an open-source software forum. Personal issues, not the right place for that. 

Engineers aren’t looking to read these posts. Software is separate from people - if someone has a issue with a person, that’s not really the fault of the open-source software. Multiple contributors maintain these projects, authors come and go. 

Social media/reddit is a better place to voice these opinions and get feedback. Software engineers.. not so much. 

Whatever is going on, it sounds intense and I do hope you find a support network & that the issues get resolved. 

Posting comments like these do more damage to the software which makes it harder to implement these tools in corporate environments. Which means the users stand less chance of being able to improve their on projects.

**Comment by stevefan1999-personal** [comment]
@ScriptedAlchemy No man just straight out report to GitHub support and sort out the matter by them.

**Comment by ScriptedAlchemy** [comment]
Can’t report on my phone, but will do when on a machine. 

Besides, I’d rather uphold OSS standards and hopefully give the user some clarity of how etiquette here works
